// Generated by https://quicktype.io
package sensor

type AwairElement struct {
	Timestamp      string  `json:"timestamp"`
	Score          int64   `json:"score"`
	DewPoint       float64 `json:"dew_point"`
	Temp           float64 `json:"temp"`
	Humid          float64 `json:"humid"`
	AbsHumid       float64 `json:"abs_humid"`
	Co2            int64   `json:"co2"`
	Co2Est         int64   `json:"co2_est"`
	Co2EstBaseline int64   `json:"co2_est_baseline"`
	Voc            int64   `json:"voc"`
	VocBaseline    int64   `json:"voc_baseline"`
	VocH2Raw       int64   `json:"voc_h2_raw"`
	VocEthanolRaw  int64   `json:"voc_ethanol_raw"`
	Pm25           int64   `json:"pm25"`
	Pm10Est        int64   `json:"pm10_est"`
}
